server:
  servlet:
    context-path: /
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.108:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  application:
    name: springboot-dubbo-provider

  dubbo:
    server: true
    registry: zookeeper://192.168.1.108:2181

  redis:
    host: 192.168.1.108
    port: 6379
    password:

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml





